# Generated by Django 3.1.4 on 2021-01-09 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20210107_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bid',
            new_name='Bids',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='listingid',
            new_name='listing_id',
        ),
        migrations.RenameField(
            model_name='bids',
            old_name='title',
            new_name='name',
        ),
    ]
