# Generated by Django 3.1.4 on 2021-01-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210109_1235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listingid',
            new_name='listing_id',
        ),
    ]
