# Generated by Django 3.1.4 on 2021-01-10 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210110_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='lis',
            name='watchers',
            field=models.ManyToManyField(blank=True, related_name='watched_listing', to=settings.AUTH_USER_MODEL),
        ),
    ]
