# Generated by Django 3.1.4 on 2021-01-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210111_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lis',
            name='watchers',
        ),
        migrations.AddField(
            model_name='lis',
            name='watchers',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
