# Generated by Django 3.1.4 on 2021-01-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_auto_20210111_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lis',
            name='watchers',
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'listing_id')},
        ),
    ]
