# Generated by Django 3.1.4 on 2021-01-13 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auto_20210112_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lis',
            old_name='link',
            new_name='img',
        ),
    ]
