# Generated by Django 3.1.4 on 2021-01-13 02:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210112_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing_id',
            field=models.IntegerField(),
        ),
    ]
