# Generated by Django 3.1.4 on 2021-01-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210112_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lis',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
