# Generated by Django 3.1.4 on 2021-01-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0027_auto_20210112_2254'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedBid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=64)),
                ('winner', models.CharField(max_length=64)),
                ('winprice', models.IntegerField()),
                ('name', models.CharField(max_length=64, null=True)),
                ('listing_id', models.IntegerField()),
            ],
        ),
    ]
