# Generated by Django 3.1.4 on 2021-01-14 20:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_closedbid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closedbid',
            name='name',
            field=models.CharField(max_length=64),
            preserve_default=False,
        ),
    ]
