# Generated by Django 3.1.4 on 2021-01-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20210115_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllLis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=32)),
                ('description', models.TextField(max_length=800)),
                ('price', models.IntegerField()),
                ('category', models.CharField(max_length=32)),
                ('img', models.CharField(blank=True, default=None, max_length=150)),
                ('date', models.DateField(auto_now=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
