# Generated by Django 3.1.4 on 2021-06-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20210619_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('hard', 'hard'), ('medium', 'medium'), ('easy', 'easy')], max_length=6),
        ),
    ]
