# Generated by Django 3.1.4 on 2021-06-19 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20210619_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('hard', 'hard'), ('medium', 'medium')], max_length=6),
        ),
    ]
