# Generated by Django 3.1.4 on 2021-06-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0007_auto_20210620_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
