# Generated by Django 3.1.4 on 2021-06-27 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0008_quiz_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'easy'), ('medium', 'medium'), ('hard', 'hard')], max_length=6),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
