# Generated by Django 3.1.4 on 2021-07-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0009_auto_20210627_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='bestscore',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='quiz',
            name='bestscoreuser',
            field=models.CharField(default=None, max_length=64),
        ),
    ]
